################################################################
#Name:  iperf3 
#Desc: YAML file for creating iperf3 server for testing.
################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server-deployment
  labels:
    app: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - master
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
#      initContainers:
#        - name: init-sysctl
#          image: busybox
#          command:
#            - sysctl
#            - -w
#            - net.ipv4.tcp_congestion_control=bbr
#          securityContext:
#            privileged: true
      containers:
      - name: iperf3-server
        #image: networkstatic/iperf3
        image: mlabbe/iperf3
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
spec:
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server
